package:
  name: pylgn
  version: {{ environ.get("GIT_STRING", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  path: ..

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools==27.2
    - numpy==1.12
    - matplotlib==2.0
    - quantities==0.11.1
    - pillow==4.1

  run:
    - python
    - setuptools==27.2
    - numpy==1.12
    - matplotlib==2.0
    - scipy==0.19
    - quantities==0.11.1
    - pillow==4.1


test:
  source_files:
    - pylgn/tests
    - docs
    - examples
  requires:
    - pytest
    - sphinx
  imports:
    - pylgn
  commands:
    - pytest -s
    - cd docs ; make doctest

about:
  home: https://github.com/miladh/pylgn/
  license: GPLv3
  license_file: LICENSE
