package:
  name: pylgn
  version: {{ environ.get("GIT_STRING", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  path: ..

build:
  script: 
    # TODO remove this and add back quantities as conda package once its updated with the new numpy API
    - pip install git+https://github.com/python-quantities/python-quantities.git
    - python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - quantities
    - pillow

  run:
    - python
    - setuptools
    - numpy 
    - matplotlib
    - scipy
    - quantities
    - pillow


test:
  source_files:
    - pylgn/tests
    - docs
    - examples
  requires:
    - pytest
    - sphinx
  imports:
    - pylgn
  commands:
    - pytest -s
    - cd docs ; make doctest

about:
  home: https://github.com/miladh/pylgn/
  license: GPLv3
  license_file: LICENSE
