package:
  name: pylgn
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  path: ..
 
build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - quantities
    - h5py
    - exdir

  run:
    - python
    - setuptools
    - numpy
    - matplotlib
    - scipy
    - quantities
    - h5py
    - exdir
    

test:
  source_files:
    - pylgn/tests
    - docs
    - examples
  requires:
    - pytest
    - sphinx
  imports:
    - pylgn
  commands:
    - pytest -s
    - cd docs ; make doctest

about:
  home: https://github.com/miladh/pylgn/
  license: GPLv3
  license_file: LICENSE
